version: "3.8"
services:
  app:
    restart: always
    build: .
    environment:
      - DOCKER_MONGO=mongo
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports: 
      - "27018:27017"