# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
        TWILIO_ACCOUNT_SID: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        TWILIO_PHONE_NUMBER: +1XXXYYYZZZZ
        TWILIO_APP_SID: APXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        API_KEY: SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        API_SECRET: XXXXXXXXXXXXXXXXX
